// <auto-generated />
using System;
using System.Collections.Generic;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250221143448_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("Core.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sku")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7323bcfb-1daa-41aa-9e53-816011102ac6"),
                            Brand = "Abba",
                            Category = "Fiskkonserver",
                            Description = "Klassisk svensk matjessill, perfekt till midsommar eller andra högtider.",
                            Image = "https://www.example.com/abba_matjessill.jpg",
                            Name = "Matjessill",
                            Sku = "abba_matjessill"
                        },
                        new
                        {
                            Id = new Guid("99b3e53c-efe0-456c-89ce-e4f42baef09a"),
                            Brand = "Kalles",
                            Category = "Fiskpålägg",
                            Description = "En svensk klassiker, krämig och smakrik kaviar gjord på torskrom.",
                            Image = "https://www.example.com/kalles_kaviar.jpg",
                            Name = "Kalles Kaviar",
                            Sku = "kalles_kaviar"
                        },
                        new
                        {
                            Id = new Guid("bf6b70d3-5ff9-4bfe-babb-dd2a5ab315d4"),
                            Brand = "Zoégas",
                            Category = "Kaffe",
                            Description = "Mörkrostat kaffe med en fyllig och kraftig smak.",
                            Image = "https://www.example.com/zoegas_skanerost.jpg",
                            Name = "Skånerost",
                            Sku = "zoegas_skanerost"
                        },
                        new
                        {
                            Id = new Guid("b7ad2594-cf46-4328-be12-6b37b42d52ee"),
                            Brand = "Arla",
                            Category = "Mjölk",
                            Description = "Svensk mellanmjölk med 1,5% fett.",
                            Image = "https://www.example.com/arla_mjolk.jpg",
                            Name = "Mellanmjölk",
                            Sku = "arla_mjolk"
                        },
                        new
                        {
                            Id = new Guid("4d5e5b20-1885-4279-bff8-ef730ff289f0"),
                            Brand = "Findus",
                            Category = "Grönsaker",
                            Description = "Frysta ärtor av hög kvalitet, perfekta som tillbehör till middagen.",
                            Image = "https://www.example.com/findus_frysta_artor.jpg",
                            Name = "Frysta Ärtor",
                            Sku = "findus_frysta_artor"
                        },
                        new
                        {
                            Id = new Guid("8d4667ea-d6b4-4252-a0ee-351737007d06"),
                            Brand = "GB Glace",
                            Category = "Glass",
                            Description = "Krämig vaniljglass, en favorit hos många.",
                            Image = "https://www.example.com/gb_glass_vanilj.jpg",
                            Name = "Vaniljglass",
                            Sku = "gb_glass_vanilj"
                        },
                        new
                        {
                            Id = new Guid("6750ba42-3371-4753-82c0-1a4e5344ade2"),
                            Brand = "Marabou",
                            Category = "Choklad",
                            Description = "En klassisk svensk mjölkchokladkaka.",
                            Image = "https://www.example.com/cloetta_marabou.jpg",
                            Name = "Marabou Mjölkchoklad",
                            Sku = "cloetta_marabou"
                        },
                        new
                        {
                            Id = new Guid("8926a5a1-437c-4ebd-b331-e6a9bfa02c5b"),
                            Brand = "Santa Maria",
                            Category = "Tex Mex",
                            Description = "Krispiga tacoskal, perfekta för att göra tacos.",
                            Image = "https://www.example.com/santa_maria_tacoskal.jpg",
                            Name = "Tacoskal",
                            Sku = "santa_maria_tacoskal"
                        },
                        new
                        {
                            Id = new Guid("bbf52a56-6a7f-42ca-adae-b41db4345d80"),
                            Brand = "Kavli",
                            Category = "Ost",
                            Description = "Krämig mjukost med olika smaker.",
                            Image = "https://www.example.com/kavli_ost.jpg",
                            Name = "Mjukost",
                            Sku = "kavli_ost"
                        },
                        new
                        {
                            Id = new Guid("b031364e-3453-4ccd-b1e5-6c0918a54db1"),
                            Brand = "Polarbröd",
                            Category = "Bröd",
                            Description = "Mjukt och smakrikt bröd från Hönö.",
                            Image = "https://www.example.com/polar_brod_honokaka.jpg",
                            Name = "Hönökaka",
                            Sku = "polar_brod_honokaka"
                        },
                        new
                        {
                            Id = new Guid("3cb591c8-d3ed-4a3c-a26a-698167c73be1"),
                            Brand = "Skansen",
                            Category = "Senap",
                            Description = "En klassisk svensk senap med en mild och söt smak.",
                            Image = "https://www.example.com/skansen_senap.jpg",
                            Name = "Skansen Senap",
                            Sku = "skansen_senap"
                        },
                        new
                        {
                            Id = new Guid("7033ae51-569f-418f-bc8a-4d2e688ab179"),
                            Brand = "Wasa",
                            Category = "Knäckebröd",
                            Description = "Ett tunt och krispigt knäckebröd, perfekt till frukost eller mellanmål.",
                            Image = "https://www.example.com/wasa_knackebrod.jpg",
                            Name = "Wasa Knäckebröd",
                            Sku = "wasa_knackebrod"
                        },
                        new
                        {
                            Id = new Guid("0481a834-44bb-4298-807e-e3ddcef6481b"),
                            Brand = "Ramlösa",
                            Category = "Mineralvatten",
                            Description = "Ett naturligt mineralvatten med kolsyra.",
                            Image = "https://www.example.com/ramlosa_vatten.jpg",
                            Name = "Ramlösa Mineralvatten",
                            Sku = "ramlosa_vatten"
                        },
                        new
                        {
                            Id = new Guid("78e46498-c10c-408a-b3c3-5a3e5684abec"),
                            Brand = "Sveriges Bästa Ägg",
                            Category = "Ägg",
                            Description = "Färska ägg från svenska gårdar.",
                            Image = "https://www.example.com/sveriges_basta_agg.jpg",
                            Name = "Ägg",
                            Sku = "sveriges_basta_agg"
                        },
                        new
                        {
                            Id = new Guid("d7e082ff-195e-4b5e-8f1b-5f503f90d1f9"),
                            Brand = "Potatis King",
                            Category = "Potatis",
                            Description = "En mjölig potatissort som är populär i Sverige.",
                            Image = "https://www.example.com/potatis_king_edward.jpg",
                            Name = "King Edward Potatis",
                            Sku = "potatis_king_edward"
                        },
                        new
                        {
                            Id = new Guid("8a8db6dc-73ad-45fa-818f-697094c1cc60"),
                            Brand = "Falu Rödfärg",
                            Category = "Färg",
                            Description = "En traditionell svensk färg som används för att måla hus.",
                            Image = "https://www.example.com/falu_rod_farg.jpg",
                            Name = "Falu Rödfärg",
                            Sku = "falu_rod_farg"
                        },
                        new
                        {
                            Id = new Guid("19dd4653-0075-43fd-afe6-591692d2ded5"),
                            Brand = "Viking",
                            Category = "Mjöl",
                            Description = "Ett svenskt mjöl som är lämpligt för bakning.",
                            Image = "https://www.example.com/viking_mjol.jpg",
                            Name = "Viking Mjöl",
                            Sku = "viking_mjol"
                        },
                        new
                        {
                            Id = new Guid("45f4ef7a-d58f-455d-a651-48d1087f0791"),
                            Brand = "Arla",
                            Category = "Mejeri",
                            Description = "En syrlig mejeriprodukt som används i matlagning.",
                            Image = "https://www.example.com/arla_graddfil.jpg",
                            Name = "Gräddfil",
                            Sku = "arla_graddfil"
                        },
                        new
                        {
                            Id = new Guid("5348eafe-24e3-4679-b78a-034b32abb48f"),
                            Brand = "Risenta",
                            Category = "Gryn",
                            Description = "Olika typer av gryn, som till exempel havregryn eller korngryn.",
                            Image = "https://www.example.com/risenta_gryn.jpg",
                            Name = "Risenta Gryn",
                            Sku = "risenta_gryn"
                        },
                        new
                        {
                            Id = new Guid("1a75693b-1d08-43f7-b4b9-18da3e0974b0"),
                            Brand = "Kockens",
                            Category = "Kryddor",
                            Description = "Ett brett utbud av kryddor för matlagning.",
                            Image = "https://www.example.com/kockens_kryddor.jpg",
                            Name = "Kockens Kryddor",
                            Sku = "kockens_kryddor"
                        },
                        new
                        {
                            Id = new Guid("1b2c3d4e-5f6a-7b8c-9d0e-1f2a3b4c5d6e"),
                            Brand = "Felix",
                            Category = "Sylt",
                            Description = "Klassisk svensk lingonsylt, perfekt till pannkakor eller köttbullar.",
                            Image = "https://www.example.com/felix_lingonsylt.jpg",
                            Name = "Lingonsylt",
                            Sku = "felix_lingonsylt"
                        },
                        new
                        {
                            Id = new Guid("2a3b4c5d-6e7f-8a9b-0c1d-2e3f4a5b6c7d"),
                            Brand = "Pågen",
                            Category = "Bröd",
                            Description = "Mörkt och smakrikt limpa bröd, perfekt till frukost.",
                            Image = "https://www.example.com/pagen_limpa.jpg",
                            Name = "Pågenlimpa",
                            Sku = "pagen_limpa"
                        },
                        new
                        {
                            Id = new Guid("3c4d5e6f-7a8b-9c0d-1e2f-3a4b5c6d7e8f"),
                            Brand = "Lurpak",
                            Category = "Mejeri",
                            Description = "Kvalitetssmör från Lurpak, perfekt för bakning och matlagning.",
                            Image = "https://www.example.com/lurpak_smor.jpg",
                            Name = "Smör",
                            Sku = "lurpak_smor"
                        },
                        new
                        {
                            Id = new Guid("4d5e6f7a-8b9c-0d1e-2f3a-4b5c6d7e8f9a"),
                            Brand = "Scan",
                            Category = "Kött",
                            Description = "En svensk klassiker, perfekt för stekning eller grillning.",
                            Image = "https://www.example.com/scan_falukorv.jpg",
                            Name = "Falukorv",
                            Sku = "scan_falukorv"
                        },
                        new
                        {
                            Id = new Guid("5e6f7a8b-9c0d-1e2f-3a4b-5c6d7e8f9a0b"),
                            Brand = "Pepsi",
                            Category = "Läsk",
                            Description = "En sockerfri läsk med en fräsch smak.",
                            Image = "https://www.example.com/pepsi_max.jpg",
                            Name = "Pepsi Max",
                            Sku = "pepsi_max"
                        },
                        new
                        {
                            Id = new Guid("6f7a8b9c-0d1e-2f3a-4b5c-6d7e8f9a0b1c"),
                            Brand = "Leksands",
                            Category = "Bröd",
                            Description = "Tunnbröd från Leksands, perfekt för smörgåsar eller mackor.",
                            Image = "https://www.example.com/leksands_tunnbrod.jpg",
                            Name = "Tunnbröd",
                            Sku = "leksands_tunnbrod"
                        },
                        new
                        {
                            Id = new Guid("7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d"),
                            Brand = "Green Giant",
                            Category = "Grönsaker",
                            Description = "Kronärtskockshjärta i vatten, perfekt för sallader eller tillbehör.",
                            Image = "https://www.example.com/green_giant_kronartskock.jpg",
                            Name = "Kronärtskockshjärta",
                            Sku = "green_giant_kronartskock"
                        },
                        new
                        {
                            Id = new Guid("8b9c0d1e-2f3a-4b5c-6d7e-8f9a0b1c2d3e"),
                            Brand = "Felix",
                            Category = "Sallad",
                            Description = "En söt och syrlig rödbetssallad, perfekt till kötträtter.",
                            Image = "https://www.example.com/felix_rodbetssallad.jpg",
                            Name = "Rödbetssallad",
                            Sku = "felix_rodbetssallad"
                        },
                        new
                        {
                            Id = new Guid("9c0d1e2f-3a4b-5c6d-7e8f-9a0b1c2d3e4f"),
                            Brand = "Gevalia",
                            Category = "Kaffe",
                            Description = "En rik och aromatisk kaffe, perfekt för morgonen.",
                            Image = "https://www.example.com/gevalia_kaffe.jpg",
                            Name = "Kaffe",
                            Sku = "gevalia_kaffe"
                        },
                        new
                        {
                            Id = new Guid("0d1e2f3a-4b5c-6d7e-8f9a-0b1c2d3e4f5a"),
                            Brand = "Barilla",
                            Category = "Pasta",
                            Description = "Klassisk italiensk pasta, perfekt för alla pastarätter.",
                            Image = "https://www.example.com/barilla_pasta.jpg",
                            Name = "Pasta",
                            Sku = "barilla_pasta"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-1234-567890abcdef"),
                            Brand = "Fazer",
                            Category = "Bröd",
                            Description = "Ett smakrikt rågbröd med en mjuk och saftig konsistens.",
                            Image = "https://www.example.com/fazer_ragbrod.jpg",
                            Name = "Rågbröd",
                            Sku = "fazer_ragbrod"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8901-2345-67890abcdefa"),
                            Brand = "ICA",
                            Category = "Kött",
                            Description = "Färdiga köttbullar, perfekta till middagen eller som tilltugg.",
                            Image = "https://www.example.com/ica_kottbullar.jpg",
                            Name = "Köttbullar",
                            Sku = "ica_kottbullar"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-9012-3456-7890abcdefab"),
                            Brand = "Coop",
                            Category = "Frukt och grönt",
                            Description = "Färska blåbär, rika på antioxidanter och smak.",
                            Image = "https://www.example.com/coop_blabar.jpg",
                            Name = "Blåbär",
                            Sku = "coop_blabar"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-0123-4567-890abcdefabc"),
                            Brand = "Arla",
                            Category = "Mejeri",
                            Description = "En naturell yoghurt utan tillsatt socker.",
                            Image = "https://www.example.com/arla_yoghurt_naturell.jpg",
                            Name = "Yoghurt Naturell",
                            Sku = "arla_yoghurt_naturell"
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-c9d0-1234-5678-90abcdefabcd"),
                            Brand = "Andersson",
                            Category = "Köksredskap",
                            Description = "En praktisk osthyvel för att skiva ost.",
                            Image = "https://www.example.com/andersson_osthyvel.jpg",
                            Name = "Osthyvel",
                            Sku = "andersson_osthyvel"
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-d0e1-2345-6789-0abcdefabcde"),
                            Brand = "Yes",
                            Category = "Hygien och rengöring",
                            Description = "Effektivt diskmedel som tar bort fett och smuts.",
                            Image = "https://www.example.com/yes_diskmedel.jpg",
                            Name = "Diskmedel",
                            Sku = "yes_diskmedel"
                        },
                        new
                        {
                            Id = new Guid("a7b8c9d0-e1f2-3456-7890-abcdefabcdef"),
                            Brand = "Lambi",
                            Category = "Hygien och rengöring",
                            Description = "Mjukt och skönt toalettpapper.",
                            Image = "https://www.example.com/lambi_toalettpapper.jpg",
                            Name = "Toalettpapper",
                            Sku = "lambi_toalettpapper"
                        },
                        new
                        {
                            Id = new Guid("b8c9d0e1-f2a3-4567-8901-bcdefabcdef0"),
                            Brand = "Oral-B",
                            Category = "Hygien och rengöring",
                            Description = "En eltandborste som ger en effektiv rengöring.",
                            Image = "https://www.example.com/oralb_tandborste.jpg",
                            Name = "Tandborste",
                            Sku = "oralb_tandborste"
                        },
                        new
                        {
                            Id = new Guid("c9d0e1f2-a3b4-5678-9012-cdefabcdef01"),
                            Brand = "Head & Shoulders",
                            Category = "Hårvård",
                            Description = "Ett schampo som motverkar mjäll och ger en frisk hårbotten.",
                            Image = "https://www.example.com/head_shoulders_schampo.jpg",
                            Name = "Schampo",
                            Sku = "head_shoulders_schampo"
                        },
                        new
                        {
                            Id = new Guid("d0e1f2a3-b4c5-6789-0123-defabcdef012"),
                            Brand = "L'Oréal",
                            Category = "Hårvård",
                            Description = "Ett balsam som gör håret mjukt och lätt att reda ut.",
                            Image = "https://www.example.com/loreal_balsam.jpg",
                            Name = "Balsam",
                            Sku = "loreal_balsam"
                        },
                        new
                        {
                            Id = new Guid("e2f3a4b5-c6d7-8901-2345-67890abcdef0"),
                            Brand = " Zeta",
                            Category = "Matolja",
                            Description = "En extra jungfru olivolja av hög kvalitet.",
                            Image = "https://www.example.com/zeta_olivolja.jpg",
                            Name = "Olivolja",
                            Sku = "zeta_olivolja"
                        },
                        new
                        {
                            Id = new Guid("f3a4b5c6-d7e8-9012-3456-7890abcdef01"),
                            Brand = "Kung Markatta",
                            Category = "Vinäger",
                            Description = "En ekologisk äppelcidervinäger.",
                            Image = "https://www.example.com/kung_markatta_vinager.jpg",
                            Name = "Vinäger",
                            Sku = "kung_markatta_vinager"
                        },
                        new
                        {
                            Id = new Guid("a4b5c6d7-e8f9-0123-4567-890abcdef012"),
                            Brand = "Kikkoman",
                            Category = "Asiatiska ingredienser",
                            Description = "En japansk sojasås med en rik och fyllig smak.",
                            Image = "https://www.example.com/kikkoman_soja.jpg",
                            Name = "Soja",
                            Sku = "kikkoman_soja"
                        },
                        new
                        {
                            Id = new Guid("b5c6d7e8-f9a0-1234-5678-90abcdef0123"),
                            Brand = "Santa Maria",
                            Category = "Kryddor",
                            Description = "En stark chilisås med en intensiv smak.",
                            Image = "https://www.example.com/santa_maria_chili.jpg",
                            Name = "Chili",
                            Sku = "santa_maria_chili"
                        },
                        new
                        {
                            Id = new Guid("c6d7e8f9-a0b1-2345-6789-0abcdef01234"),
                            Brand = "Biodlingarna",
                            Category = "Honung",
                            Description = "En svensk honung med en söt och mild smak.",
                            Image = "https://www.example.com/biodlingarna_honung.jpg",
                            Name = "Honung",
                            Sku = "biodlingarna_honung"
                        },
                        new
                        {
                            Id = new Guid("d7e8f9a0-b1c2-3456-7890-abcdef012345"),
                            Brand = "Falksalt",
                            Category = "Kryddor",
                            Description = "Ett havssalt med en ren och naturlig smak.",
                            Image = "https://www.example.com/falksalt_salt.jpg",
                            Name = "Salt",
                            Sku = "falksalt_salt"
                        },
                        new
                        {
                            Id = new Guid("e8f9a0b1-c2d3-4567-8901-bcdef0123456"),
                            Brand = "Santa Maria",
                            Category = "Kryddor",
                            Description = "En svartpeppar med en stark och aromatisk smak.",
                            Image = "https://www.example.com/santa_maria_peppar.jpg",
                            Name = "Peppar",
                            Sku = "santa_maria_peppar"
                        },
                        new
                        {
                            Id = new Guid("f9a0b1c2-d3e4-5678-9012-cdef01234567"),
                            Brand = "Slotts",
                            Category = "Kryddor",
                            Description = "En svensk senap med en mild och söt smak.",
                            Image = "https://www.example.com/slotts_senap.jpg",
                            Name = "Senap",
                            Sku = "slotts_senap"
                        },
                        new
                        {
                            Id = new Guid("a0b1c2d3-e4f5-6789-0123-def012345678"),
                            Brand = "Felix",
                            Category = "Kryddor",
                            Description = "En svensk ketchup med en söt och syrlig smak.",
                            Image = "https://www.example.com/felix_ketchup.jpg",
                            Name = "Ketchup",
                            Sku = "felix_ketchup"
                        },
                        new
                        {
                            Id = new Guid("b1c2d3e4-f5a6-7890-1234-ef0123456789"),
                            Brand = "Hellmann's",
                            Category = "Kryddor",
                            Description = "En krämig majonnäs med en rik och fyllig smak.",
                            Image = "https://www.example.com/hellmanns_majonnas.jpg",
                            Name = "Majonnäs",
                            Sku = "hellmanns_majonnas"
                        },
                        new
                        {
                            Id = new Guid("c2d3e4f5-a6b7-8901-2345-f01234567890"),
                            Brand = "Felix",
                            Category = "Kryddor",
                            Description = "En dansk remouladsås med en söt, syrlig och kryddig smak.",
                            Image = "https://www.example.com/felix_remouladsas.jpg",
                            Name = "Remouladsås",
                            Sku = "felix_remouladsas"
                        },
                        new
                        {
                            Id = new Guid("d3e4f5a6-b7c8-9012-3456-01234567890a"),
                            Brand = "Podravka",
                            Category = "Kryddor",
                            Description = "En smakrik relish gjord på paprika, aubergine och chili.",
                            Image = "https://www.example.com/podravka_ajvar.jpg",
                            Name = "Ajvar Relish",
                            Sku = "podravka_ajvar"
                        },
                        new
                        {
                            Id = new Guid("e4f5a6b7-c8d9-0123-4567-1234567890ab"),
                            Brand = "Barilla",
                            Category = "Pasta",
                            Description = "En italiensk pesto med en smak av basilika, pinjenötter och parmesanost.",
                            Image = "https://www.example.com/barilla_pesto.jpg",
                            Name = "Pesto",
                            Sku = "barilla_pesto"
                        },
                        new
                        {
                            Id = new Guid("f5a6b7c8-d9e0-2345-6789-234567890abc"),
                            Brand = "Nicolas Vahé",
                            Category = "Delikatesser",
                            Description = "En fransk tapenade gjord på oliver, kapris och ansjovis.",
                            Image = "https://www.example.com/nicolas_vahe_tapenade.jpg",
                            Name = "Tapenade",
                            Sku = "nicolas_vahe_tapenade"
                        },
                        new
                        {
                            Id = new Guid("a6b7c8d9-e0f1-3456-7890-34567890abcd"),
                            Brand = "St Michel",
                            Category = "Frukost",
                            Description = "En fransk marmelad med en smak av apelsin och citron.",
                            Image = "https://www.example.com/st_michel_marmelad.jpg",
                            Name = "Marmelad",
                            Sku = "st_michel_marmelad"
                        },
                        new
                        {
                            Id = new Guid("b18bdff4-1e60-42c5-8ae0-92b62513ece1"),
                            Brand = "Arla",
                            Category = "Mejeri",
                            Description = "Färsk mjölk med hög kvalitet, perfekt för frukost eller bakning.",
                            Image = "https://www.example.com/arla_mjolk.jpg",
                            Name = "Mjölk",
                            Sku = "arla_standard_mjolk"
                        },
                        new
                        {
                            Id = new Guid("8c7f6994-15a4-4183-8752-27ab45a2f13c"),
                            Brand = "Lurpak",
                            Category = "Mejeri",
                            Description = "Ett smör med en rik och krämig smak, perfekt för matlagning och bakning.",
                            Image = "https://www.example.com/lurpak_smor.jpg",
                            Name = "Smör",
                            Sku = "lurpak_smor"
                        },
                        new
                        {
                            Id = new Guid("c944f005-afcd-4498-8703-6635ba0dd95c"),
                            Brand = "Kronägg",
                            Category = "Mejeri",
                            Description = "Färska ägg från frigående höns, perfekta för frukost eller bakning.",
                            Image = "https://www.example.com/kronagg_agg.jpg",
                            Name = "Ägg",
                            Sku = "kronagg_agg"
                        },
                        new
                        {
                            Id = new Guid("9546816f-4bef-4772-b098-01d440d92964"),
                            Brand = "Uncle Ben's",
                            Category = "Torrvaror",
                            Description = "Ett långkornigt ris som är perfekt för alla typer av maträtter.",
                            Image = "https://www.example.com/uncle_bens_ris.jpg",
                            Name = "Ris",
                            Sku = "uncle_bens_ris"
                        },
                        new
                        {
                            Id = new Guid("45eea981-3a74-41bb-b5bb-c55ce2078c46"),
                            Brand = "Gevalia",
                            Category = "Drycker",
                            Description = "Ett mörkrostad kaffe med en rik och aromatisk smak.",
                            Image = "https://www.example.com/gevalia_kaffe.jpg",
                            Name = "Kaffe",
                            Sku = "gevalia_kaffe"
                        },
                        new
                        {
                            Id = new Guid("36612848-7709-4821-99b7-ebb25ddfc679"),
                            Brand = "Lipton",
                            Category = "Drycker",
                            Description = "Ett svart te med en frisk och uppiggande smak.",
                            Image = "https://www.example.com/lipton_te.jpg",
                            Name = "Te",
                            Sku = "lipton_te"
                        },
                        new
                        {
                            Id = new Guid("59b8c04e-47dd-4fca-8659-9499d8e422fa"),
                            Brand = "Marabou",
                            Category = "Godis",
                            Description = "En mjölkchoklad med en krämig och söt smak.",
                            Image = "https://www.example.com/marabou_choklad.jpg",
                            Name = "Choklad",
                            Sku = "marabou_choklad"
                        },
                        new
                        {
                            Id = new Guid("7eec1f41-ecc1-4659-ad6f-e571f97076be"),
                            Brand = "Oreo",
                            Category = "Godis",
                            Description = "Klassiska kex med en krämig vaniljfyllning.",
                            Image = "https://www.example.com/oreo_kex.jpg",
                            Name = "Kex",
                            Sku = "oreo_kex"
                        },
                        new
                        {
                            Id = new Guid("c61a046b-e3ef-4603-ad60-a0879c9151c7"),
                            Brand = "OLW",
                            Category = "Snacks",
                            Description = "Ett saltade chips med en krispig och smakrik konsistens.",
                            Image = "https://www.example.com/olw_chips.jpg",
                            Name = "Chips",
                            Sku = "olw_chips"
                        },
                        new
                        {
                            Id = new Guid("a135bd8a-755e-459c-81f2-2e42c9aed909"),
                            Brand = "Estrella",
                            Category = "Snacks",
                            Description = "Ett saltat popcorn med en lätt och luftig konsistens.",
                            Image = "https://www.example.com/estrella_popcorn.jpg",
                            Name = "Popcorn",
                            Sku = "estrella_popcorn"
                        });
                });

            modelBuilder.Entity("Core.Entities.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("GrpcAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.ComplexProperty<Dictionary<string, object>>("Location", "Core.Entities.Store.Location#Coordinates", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Latitude")
                                .HasColumnType("REAL");

                            b1.Property<double>("Longitude")
                                .HasColumnType("REAL");
                        });

                    b.HasKey("Id");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("Core.Entities.StoreInventory", b =>
                {
                    b.Property<Guid>("StoreId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("StoreId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("Core.Entities.StoreInventory", b =>
                {
                    b.HasOne("Core.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Store");
                });
#pragma warning restore 612, 618
        }
    }
}
